name: '[Util] Auto Assign PR'

on:
  pull_request:
    types: [opened, ready_for_review]

# ${{ secrets.GITHUB_TOKEN }} に必要な権限を付与する。
permissions:
  contents: read
  pull-requests: write

jobs:
  assign:
    runs-on: ubuntu-latest

    steps:
      # .github/auto_assign.yml の設定に従って Reviewer と Assignee を自動的に追加する。
      - uses: kentaro-m/auto-assign-action@v2.0.0
