# 参考：
#
# - https://docs.anthropic.com/ja/docs/claude-code/github-actions
# - https://github.com/anthropics/claude-code-action/blob/main/examples/claude.yml
name: '[Util] Claude PR Assistant'

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]

jobs:
  claude-code-action:
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@claude')) ||
      (github.event_name == 'issues' && contains(github.event.issue.body, '@claude'))
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run Claude PR Action
        uses: kosukesaigusa/claude-code-action-access-control@v0.0.2
        with:
          allowed_users: |
            kosukesaigusa
          # anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          # MAX プランでサブスクしている Claude アカウントで claude setup-token を実行した結果得られる OAuth トークンを使用する。
          # 有効期限は 1 年間である。

          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          timeout_minutes: "60"
          allowed_tools: |
            Bash(bun run check)
            Bash(bun run test:ci)
          # mode: tag  # Default: responds to @claude mentions
          # Optional: Restrict network access to specific domains only
          experimental_allowed_domains: |
            .anthropic.com
            .github.com
            api.github.com
            .githubusercontent.com
            bun.sh
            registry.npmjs.org
